# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.15.+

# Dependencies
fabric_version=0.152.2+26.2
plasmid_version=0.7.2-SNAPSHOT+26.2

# Mod Properties
mod_version=0.2.3
maven_group=supercoder79
archives_base_name=wavedefense
